### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by lnorton89** [xxhomey19/bootstrap-webpack-jquery-boilerplate#3]
I'm getting errors when referencing images in my SASS. I see file-loader is not in the package.json. Is there a reason for this?

`ERROR in ./public/header.png
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.loader (/mnt/c/Users/Lawrence/Documents/Web Dev/sandbox/woolywash/node_modules/url-loader/dist/index.js:59:20)
 @ ./src/scss/index.scss (./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./src/scss/index.scss) 7:170422-170456
 @ ./src/scss/index.scss
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./public/header-mobile.png
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.loader (/mnt/c/Users/Lawrence/Documents/Web Dev/sandbox/woolywash/node_modules/url-loader/dist/index.js:59:20)
 @ ./src/scss/index.scss (./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./src/scss/index.scss) 7:170741-170782
 @ ./src/scss/index.scss
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js`

**Comment by xxhomey19** [comment]
Hi @lnorton89 
No, I just didn't use it when I created this boilerplate. It would be awesome if you could send a PR with `file-loader` and use it.

**Comment by lnorton89** [comment]
I've added it to my project I'm using it in, when I get time I'll try to figure out a pull request and do it. Thanks for the reply.
